// Admin Portal Mock Data

export interface AdminStatCard {
  label: string;
  value: string;
  change: string;
  changeType: 'up' | 'down';
}

export interface RevenueData {
  month: string;
  revenue: number;
  growth: number;
}

export interface RecentActivity {
  id: string;
  description: string;
  timestamp: string;
  type: 'user' | 'payment' | 'business' | 'ai' | 'system' | 'invoice';
}

export interface ActivityLog {
  id: string;
  performer: string;
  performerEmail: string;
  role: 'admin' | 'manager' | 'support' | 'billing';
  action: string;
  target: string;
  timestamp: Date;
  category: 'user' | 'billing' | 'business' | 'system' | 'ai';
}

export interface Business {
  id: string;
  fullName: string;
  email: string;
  businessName: string;
  plan: 'Free' | 'Starter' | 'Pro' | 'Enterprise';
  status: 'active' | 'suspended' | 'pending';
  dateJoined: Date;
}

const now = new Date();
const currentMonth = now.getMonth();
const currentYear = now.getFullYear();

function getMonthName(offset: number): string {
  const d = new Date(currentYear, currentMonth - offset, 1);
  return d.toLocaleString('default', { month: 'short' });
}

export const revenueData: RevenueData[] = [
  { month: getMonthName(5), revenue: 42000, growth: 8 },
  { month: getMonthName(4), revenue: 48500, growth: 15 },
  { month: getMonthName(3), revenue: 51200, growth: 6 },
  { month: getMonthName(2), revenue: 55800, growth: 9 },
  { month: getMonthName(1), revenue: 62300, growth: 12 },
  { month: getMonthName(0), revenue: 68700, growth: 10 },
];

export const recentActivities: RecentActivity[] = [
  {
    id: 'ra1',
    description: "New business 'TechNova Inc.' registered",
    timestamp: '12 min ago',
    type: 'business',
  },
  {
    id: 'ra2',
    description: 'Payment of $4,200 received from CloudBase',
    timestamp: '34 min ago',
    type: 'payment',
  },
  {
    id: 'ra3',
    description: 'AI query limit increased for DesignCraft',
    timestamp: '1 hr ago',
    type: 'ai',
  },
  {
    id: 'ra4',
    description: 'User john@acme.com upgraded to Pro plan',
    timestamp: '2 hrs ago',
    type: 'user',
  },
  {
    id: 'ra5',
    description: 'System backup completed successfully',
    timestamp: '3 hrs ago',
    type: 'system',
  },
  {
    id: 'ra6',
    description: 'Invoice #INV-1042 generated for Servix Solutions',
    timestamp: '4 hrs ago',
    type: 'invoice',
  },
];

export const activityLogs: ActivityLog[] = [
  {
    id: 'al1',
    performer: 'Sarah Chen',
    performerEmail: 'sarah@servixos.com',
    role: 'admin',
    action: 'Created new business account',
    target: 'TechNova Inc.',
    timestamp: new Date(Date.now() - 720000),
    category: 'business',
  },
  {
    id: 'al2',
    performer: 'James Wilson',
    performerEmail: 'james@servixos.com',
    role: 'billing',
    action: 'Processed refund',
    target: 'Invoice #INV-1038 — $850',
    timestamp: new Date(Date.now() - 2040000),
    category: 'billing',
  },
  {
    id: 'al3',
    performer: 'Maria Lopez',
    performerEmail: 'maria@servixos.com',
    role: 'support',
    action: 'Resolved support ticket',
    target: 'Ticket #4521 — Login issue',
    timestamp: new Date(Date.now() - 3600000),
    category: 'system',
  },
  {
    id: 'al4',
    performer: 'Sarah Chen',
    performerEmail: 'sarah@servixos.com',
    role: 'admin',
    action: 'Updated AI query limits',
    target: 'DesignCraft Studio — 10,000/day',
    timestamp: new Date(Date.now() - 5400000),
    category: 'ai',
  },
  {
    id: 'al5',
    performer: 'David Kim',
    performerEmail: 'david@servixos.com',
    role: 'manager',
    action: 'Approved business verification',
    target: 'CloudBase Technologies',
    timestamp: new Date(Date.now() - 7200000),
    category: 'business',
  },
  {
    id: 'al6',
    performer: 'James Wilson',
    performerEmail: 'james@servixos.com',
    role: 'billing',
    action: 'Generated monthly invoice',
    target: 'Invoice #INV-1042 — Servix Solutions',
    timestamp: new Date(Date.now() - 10800000),
    category: 'billing',
  },
  {
    id: 'al7',
    performer: 'Sarah Chen',
    performerEmail: 'sarah@servixos.com',
    role: 'admin',
    action: 'Suspended user account',
    target: 'spam-user@fake.com',
    timestamp: new Date(Date.now() - 14400000),
    category: 'user',
  },
  {
    id: 'al8',
    performer: 'Maria Lopez',
    performerEmail: 'maria@servixos.com',
    role: 'support',
    action: 'Escalated support ticket',
    target: 'Ticket #4519 — Payment failure',
    timestamp: new Date(Date.now() - 18000000),
    category: 'system',
  },
  {
    id: 'al9',
    performer: 'David Kim',
    performerEmail: 'david@servixos.com',
    role: 'manager',
    action: 'Updated subscription plan',
    target: 'Acme Corp — Enterprise tier',
    timestamp: new Date(Date.now() - 21600000),
    category: 'billing',
  },
  {
    id: 'al10',
    performer: 'Sarah Chen',
    performerEmail: 'sarah@servixos.com',
    role: 'admin',
    action: 'Deployed system update',
    target: 'v2.4.1 — Performance improvements',
    timestamp: new Date(Date.now() - 25200000),
    category: 'system',
  },
  {
    id: 'al11',
    performer: 'James Wilson',
    performerEmail: 'james@servixos.com',
    role: 'billing',
    action: 'Sent payment reminder',
    target: '3 overdue invoices',
    timestamp: new Date(Date.now() - 43200000),
    category: 'billing',
  },
  {
    id: 'al12',
    performer: 'David Kim',
    performerEmail: 'david@servixos.com',
    role: 'manager',
    action: 'Onboarded new client',
    target: 'Stellar Dynamics LLC',
    timestamp: new Date(Date.now() - 50400000),
    category: 'business',
  },
  {
    id: 'al13',
    performer: 'Maria Lopez',
    performerEmail: 'maria@servixos.com',
    role: 'support',
    action: 'Updated knowledge base article',
    target: 'How to connect API keys',
    timestamp: new Date(Date.now() - 64800000),
    category: 'system',
  },
  {
    id: 'al14',
    performer: 'Sarah Chen',
    performerEmail: 'sarah@servixos.com',
    role: 'admin',
    action: 'Reset user password',
    target: 'client@cloudbase.io',
    timestamp: new Date(Date.now() - 86400000),
    category: 'user',
  },
  {
    id: 'al15',
    performer: 'James Wilson',
    performerEmail: 'james@servixos.com',
    role: 'billing',
    action: 'Applied discount code',
    target: 'LAUNCH25 — 25% off for TechNova',
    timestamp: new Date(Date.now() - 90000000),
    category: 'billing',
  },
  {
    id: 'al16',
    performer: 'David Kim',
    performerEmail: 'david@servixos.com',
    role: 'manager',
    action: 'Reviewed AI usage report',
    target: 'March 2026 — 1.2M queries',
    timestamp: new Date(Date.now() - 100800000),
    category: 'ai',
  },
  {
    id: 'al17',
    performer: 'Sarah Chen',
    performerEmail: 'sarah@servixos.com',
    role: 'admin',
    action: 'Added new team member',
    target: 'alex@servixos.com — Support role',
    timestamp: new Date(Date.now() - 129600000),
    category: 'user',
  },
  {
    id: 'al18',
    performer: 'Maria Lopez',
    performerEmail: 'maria@servixos.com',
    role: 'support',
    action: 'Closed batch of resolved tickets',
    target: '12 tickets auto-closed',
    timestamp: new Date(Date.now() - 172800000),
    category: 'system',
  },
  // 20 additional entries
  {
    id: 'al19',
    performer: 'Sarah Chen',
    performerEmail: 'sarah@servixos.com',
    role: 'admin',
    action: 'Enabled two-factor authentication',
    target: 'Platform-wide enforcement',
    timestamp: new Date(Date.now() - 180000000),
    category: 'system',
  },
  {
    id: 'al20',
    performer: 'James Wilson',
    performerEmail: 'james@servixos.com',
    role: 'billing',
    action: 'Issued credit note',
    target: 'Credit #CN-0087 — $320 for Acme Corp',
    timestamp: new Date(Date.now() - 190000000),
    category: 'billing',
  },
  {
    id: 'al21',
    performer: 'David Kim',
    performerEmail: 'david@servixos.com',
    role: 'manager',
    action: 'Approved new partner integration',
    target: 'Zapier connector — beta access',
    timestamp: new Date(Date.now() - 200000000),
    category: 'business',
  },
  {
    id: 'al22',
    performer: 'Maria Lopez',
    performerEmail: 'maria@servixos.com',
    role: 'support',
    action: 'Merged duplicate accounts',
    target: 'john@acme.com + john.doe@acme.com',
    timestamp: new Date(Date.now() - 210000000),
    category: 'user',
  },
  {
    id: 'al23',
    performer: 'Sarah Chen',
    performerEmail: 'sarah@servixos.com',
    role: 'admin',
    action: 'Configured rate limiting',
    target: 'API — 1,000 req/min per client',
    timestamp: new Date(Date.now() - 220000000),
    category: 'system',
  },
  {
    id: 'al24',
    performer: 'James Wilson',
    performerEmail: 'james@servixos.com',
    role: 'billing',
    action: 'Updated tax configuration',
    target: 'EU VAT rates — 2026 Q2',
    timestamp: new Date(Date.now() - 230000000),
    category: 'billing',
  },
  {
    id: 'al25',
    performer: 'David Kim',
    performerEmail: 'david@servixos.com',
    role: 'manager',
    action: 'Completed quarterly review',
    target: 'Q1 2026 — 34% growth',
    timestamp: new Date(Date.now() - 240000000),
    category: 'business',
  },
  {
    id: 'al26',
    performer: 'Maria Lopez',
    performerEmail: 'maria@servixos.com',
    role: 'support',
    action: 'Created canned response template',
    target: 'Billing FAQ — 5 new templates',
    timestamp: new Date(Date.now() - 250000000),
    category: 'system',
  },
  {
    id: 'al27',
    performer: 'Sarah Chen',
    performerEmail: 'sarah@servixos.com',
    role: 'admin',
    action: 'Revoked API key',
    target: 'Key #ak-9281 — Compromised credentials',
    timestamp: new Date(Date.now() - 260000000),
    category: 'system',
  },
  {
    id: 'al28',
    performer: 'James Wilson',
    performerEmail: 'james@servixos.com',
    role: 'billing',
    action: 'Processed bulk payment',
    target: '12 invoices — $28,400 total',
    timestamp: new Date(Date.now() - 270000000),
    category: 'billing',
  },
  {
    id: 'al29',
    performer: 'David Kim',
    performerEmail: 'david@servixos.com',
    role: 'manager',
    action: 'Assigned account manager',
    target: 'Lisa Park → Stellar Dynamics LLC',
    timestamp: new Date(Date.now() - 280000000),
    category: 'business',
  },
  {
    id: 'al30',
    performer: 'Maria Lopez',
    performerEmail: 'maria@servixos.com',
    role: 'support',
    action: 'Escalated to engineering',
    target: 'Bug #7823 — Data sync failure',
    timestamp: new Date(Date.now() - 290000000),
    category: 'system',
  },
  {
    id: 'al31',
    performer: 'Sarah Chen',
    performerEmail: 'sarah@servixos.com',
    role: 'admin',
    action: 'Updated privacy policy',
    target: 'v3.1 — GDPR compliance update',
    timestamp: new Date(Date.now() - 300000000),
    category: 'system',
  },
  {
    id: 'al32',
    performer: 'James Wilson',
    performerEmail: 'james@servixos.com',
    role: 'billing',
    action: 'Adjusted pricing tier',
    target: 'Pro plan — $49/mo → $59/mo',
    timestamp: new Date(Date.now() - 310000000),
    category: 'billing',
  },
  {
    id: 'al33',
    performer: 'David Kim',
    performerEmail: 'david@servixos.com',
    role: 'manager',
    action: 'Verified business documents',
    target: 'NovaTech Solutions — Tax ID verified',
    timestamp: new Date(Date.now() - 320000000),
    category: 'business',
  },
  {
    id: 'al34',
    performer: 'Maria Lopez',
    performerEmail: 'maria@servixos.com',
    role: 'support',
    action: 'Responded to feedback survey',
    target: 'NPS score 72 — Action items logged',
    timestamp: new Date(Date.now() - 330000000),
    category: 'system',
  },
  {
    id: 'al35',
    performer: 'Sarah Chen',
    performerEmail: 'sarah@servixos.com',
    role: 'admin',
    action: 'Migrated database schema',
    target: 'v2.5.0 — Added analytics tables',
    timestamp: new Date(Date.now() - 340000000),
    category: 'system',
  },
  {
    id: 'al36',
    performer: 'James Wilson',
    performerEmail: 'james@servixos.com',
    role: 'billing',
    action: 'Exported financial report',
    target: 'Q1 2026 — Revenue summary PDF',
    timestamp: new Date(Date.now() - 350000000),
    category: 'billing',
  },
  {
    id: 'al37',
    performer: 'David Kim',
    performerEmail: 'david@servixos.com',
    role: 'manager',
    action: 'Scheduled product demo',
    target: 'MegaCorp Industries — April 18',
    timestamp: new Date(Date.now() - 360000000),
    category: 'business',
  },
  {
    id: 'al38',
    performer: 'Maria Lopez',
    performerEmail: 'maria@servixos.com',
    role: 'support',
    action: 'Published help center update',
    target: 'New onboarding guide — 8 articles',
    timestamp: new Date(Date.now() - 370000000),
    category: 'system',
  },
];

export const businesses: Business[] = [
  {
    id: 'b1',
    fullName: 'John Carter',
    email: 'john@technova.io',
    businessName: 'TechNova Inc.',
    plan: 'Enterprise',
    status: 'active',
    dateJoined: new Date('2024-03-15'),
  },
  {
    id: 'b2',
    fullName: 'Emily Zhang',
    email: 'emily@cloudbase.io',
    businessName: 'CloudBase Technologies',
    plan: 'Pro',
    status: 'active',
    dateJoined: new Date('2024-05-22'),
  },
  {
    id: 'b3',
    fullName: 'Marcus Thompson',
    email: 'marcus@designcraft.co',
    businessName: 'DesignCraft Studio',
    plan: 'Pro',
    status: 'active',
    dateJoined: new Date('2024-06-10'),
  },
  {
    id: 'b4',
    fullName: 'Priya Sharma',
    email: 'priya@servix.solutions',
    businessName: 'Servix Solutions',
    plan: 'Enterprise',
    status: 'active',
    dateJoined: new Date('2024-01-08'),
  },
  {
    id: 'b5',
    fullName: 'Alex Rivera',
    email: 'alex@stellar.llc',
    businessName: 'Stellar Dynamics LLC',
    plan: 'Starter',
    status: 'active',
    dateJoined: new Date('2025-01-20'),
  },
  {
    id: 'b6',
    fullName: 'Sophie Martin',
    email: 'sophie@novatech.com',
    businessName: 'NovaTech Solutions',
    plan: 'Pro',
    status: 'pending',
    dateJoined: new Date('2026-03-28'),
  },
  {
    id: 'b7',
    fullName: 'David Park',
    email: 'david@megacorp.io',
    businessName: 'MegaCorp Industries',
    plan: 'Enterprise',
    status: 'active',
    dateJoined: new Date('2023-11-05'),
  },
  {
    id: 'b8',
    fullName: 'Laura Bennett',
    email: 'laura@pixelwave.co',
    businessName: 'PixelWave Creative',
    plan: 'Starter',
    status: 'suspended',
    dateJoined: new Date('2025-06-14'),
  },
  {
    id: 'b9',
    fullName: "Ryan O'Brien",
    email: 'ryan@dataflow.ai',
    businessName: 'DataFlow AI',
    plan: 'Pro',
    status: 'active',
    dateJoined: new Date('2024-09-03'),
  },
  {
    id: 'b10',
    fullName: 'Aisha Patel',
    email: 'aisha@greenleaf.eco',
    businessName: 'GreenLeaf Eco',
    plan: 'Free',
    status: 'active',
    dateJoined: new Date('2026-01-12'),
  },
  {
    id: 'b11',
    fullName: 'Tom Fischer',
    email: 'tom@buildright.dev',
    businessName: 'BuildRight Dev',
    plan: 'Pro',
    status: 'active',
    dateJoined: new Date('2024-11-17'),
  },
  {
    id: 'b12',
    fullName: 'Nina Kowalski',
    email: 'nina@brightpath.io',
    businessName: 'BrightPath Analytics',
    plan: 'Enterprise',
    status: 'active',
    dateJoined: new Date('2024-02-25'),
  },
  {
    id: 'b13',
    fullName: 'Carlos Mendez',
    email: 'carlos@quickship.co',
    businessName: 'QuickShip Logistics',
    plan: 'Starter',
    status: 'active',
    dateJoined: new Date('2025-04-09'),
  },
  {
    id: 'b14',
    fullName: 'Hannah Lee',
    email: 'hannah@artisan.market',
    businessName: 'Artisan Market',
    plan: 'Free',
    status: 'pending',
    dateJoined: new Date('2026-04-01'),
  },
  {
    id: 'b15',
    fullName: 'Oliver Grant',
    email: 'oliver@securelock.io',
    businessName: 'SecureLock Systems',
    plan: 'Enterprise',
    status: 'active',
    dateJoined: new Date('2023-08-20'),
  },
  {
    id: 'b16',
    fullName: 'Fatima Al-Rashid',
    email: 'fatima@zenith.tech',
    businessName: 'Zenith Technologies',
    plan: 'Pro',
    status: 'suspended',
    dateJoined: new Date('2024-07-30'),
  },
  {
    id: 'b17',
    fullName: 'Jake Morrison',
    email: 'jake@freshbyte.io',
    businessName: 'FreshByte Apps',
    plan: 'Starter',
    status: 'active',
    dateJoined: new Date('2025-09-11'),
  },
  {
    id: 'b18',
    fullName: 'Chloe Dubois',
    email: 'chloe@luxeinterior.com',
    businessName: 'Luxe Interior Design',
    plan: 'Pro',
    status: 'active',
    dateJoined: new Date('2024-12-05'),
  },
  {
    id: 'b19',
    fullName: 'Wei Chen',
    email: 'wei@quantumedge.ai',
    businessName: 'QuantumEdge AI',
    plan: 'Enterprise',
    status: 'active',
    dateJoined: new Date('2023-06-15'),
  },
  {
    id: 'b20',
    fullName: 'Megan Scott',
    email: 'megan@bloomhealth.co',
    businessName: 'BloomHealth',
    plan: 'Starter',
    status: 'active',
    dateJoined: new Date('2025-02-18'),
  },
  {
    id: 'b21',
    fullName: 'Liam Nguyen',
    email: 'liam@codeforge.dev',
    businessName: 'CodeForge Studios',
    plan: 'Pro',
    status: 'active',
    dateJoined: new Date('2024-08-22'),
  },
  {
    id: 'b22',
    fullName: 'Isabella Romano',
    email: 'isabella@vitaverde.eu',
    businessName: 'VitaVerde Organics',
    plan: 'Free',
    status: 'active',
    dateJoined: new Date('2026-02-10'),
  },
  {
    id: 'b23',
    fullName: 'Nathan Brooks',
    email: 'nathan@skyline.build',
    businessName: 'Skyline Construction',
    plan: 'Enterprise',
    status: 'active',
    dateJoined: new Date('2023-12-01'),
  },
  {
    id: 'b24',
    fullName: 'Zara Khan',
    email: 'zara@pulsefit.io',
    businessName: 'PulseFit Wellness',
    plan: 'Starter',
    status: 'pending',
    dateJoined: new Date('2026-03-15'),
  },
  {
    id: 'b25',
    fullName: 'Ethan Wolfe',
    email: 'ethan@ironcladops.com',
    businessName: 'IronClad Operations',
    plan: 'Pro',
    status: 'suspended',
    dateJoined: new Date('2024-10-28'),
  },
];

export function getAdminStats() {
  return {
    totalUsers: { value: '12,847', change: '+12%', changeType: 'up' as const },
    monthlyRevenue: { value: '$68,700', change: '+10%', changeType: 'up' as const },
    activeBusinesses: { value: '342', change: '+5%', changeType: 'up' as const },
    aiQueriesToday: { value: '48,291', change: '+23%', changeType: 'up' as const },
  };
}
