export type UserRole = 'owner' | 'admin' | 'manager' | 'employee';
export type UserStatus = 'active' | 'suspended' | 'pending';

export interface User {
  id: string;
  fullName: string;
  email: string;
  role: UserRole;
  businessName: string;
  businessId: string;
  status: UserStatus;
  dateJoined: Date;
  lastActive: Date;
}

const now = Date.now();
const day = 86400000;

export const users: User[] = [
  {
    id: 'u1',
    fullName: 'John Carter',
    email: 'john@technova.io',
    role: 'owner',
    businessName: 'TechNova Inc.',
    businessId: 'b1',
    status: 'active',
    dateJoined: new Date('2024-03-15'),
    lastActive: new Date(now - day * 0.2),
  },
  {
    id: 'u2',
    fullName: 'Alice Wang',
    email: 'alice@technova.io',
    role: 'admin',
    businessName: 'TechNova Inc.',
    businessId: 'b1',
    status: 'active',
    dateJoined: new Date('2024-04-10'),
    lastActive: new Date(now - day * 1),
  },
  {
    id: 'u3',
    fullName: 'Tom Harris',
    email: 'tom@technova.io',
    role: 'employee',
    businessName: 'TechNova Inc.',
    businessId: 'b1',
    status: 'active',
    dateJoined: new Date('2024-06-01'),
    lastActive: new Date(now - day * 3),
  },
  {
    id: 'u4',
    fullName: 'Emily Zhang',
    email: 'emily@cloudbase.io',
    role: 'owner',
    businessName: 'CloudBase Technologies',
    businessId: 'b2',
    status: 'active',
    dateJoined: new Date('2024-05-22'),
    lastActive: new Date(now - day * 0.5),
  },
  {
    id: 'u5',
    fullName: 'Kevin Liu',
    email: 'kevin@cloudbase.io',
    role: 'manager',
    businessName: 'CloudBase Technologies',
    businessId: 'b2',
    status: 'active',
    dateJoined: new Date('2024-07-15'),
    lastActive: new Date(now - day * 2),
  },
  {
    id: 'u6',
    fullName: 'Sarah Green',
    email: 'sarah@cloudbase.io',
    role: 'employee',
    businessName: 'CloudBase Technologies',
    businessId: 'b2',
    status: 'suspended',
    dateJoined: new Date('2024-08-20'),
    lastActive: new Date(now - day * 30),
  },
  {
    id: 'u7',
    fullName: 'Marcus Thompson',
    email: 'marcus@designcraft.co',
    role: 'owner',
    businessName: 'DesignCraft Studio',
    businessId: 'b3',
    status: 'active',
    dateJoined: new Date('2024-06-10'),
    lastActive: new Date(now - day * 0.1),
  },
  {
    id: 'u8',
    fullName: 'Lily Chen',
    email: 'lily@designcraft.co',
    role: 'employee',
    businessName: 'DesignCraft Studio',
    businessId: 'b3',
    status: 'active',
    dateJoined: new Date('2024-09-05'),
    lastActive: new Date(now - day * 4),
  },
  {
    id: 'u9',
    fullName: 'Priya Sharma',
    email: 'priya@servix.solutions',
    role: 'owner',
    businessName: 'Servix Solutions',
    businessId: 'b4',
    status: 'active',
    dateJoined: new Date('2024-01-08'),
    lastActive: new Date(now - day * 0.3),
  },
  {
    id: 'u10',
    fullName: 'Ravi Patel',
    email: 'ravi@servix.solutions',
    role: 'admin',
    businessName: 'Servix Solutions',
    businessId: 'b4',
    status: 'active',
    dateJoined: new Date('2024-02-15'),
    lastActive: new Date(now - day * 1),
  },
  {
    id: 'u11',
    fullName: 'Nina Kapoor',
    email: 'nina@servix.solutions',
    role: 'employee',
    businessName: 'Servix Solutions',
    businessId: 'b4',
    status: 'pending',
    dateJoined: new Date('2026-04-01'),
    lastActive: new Date(now - day * 0),
  },
  {
    id: 'u12',
    fullName: 'Alex Rivera',
    email: 'alex@stellar.llc',
    role: 'owner',
    businessName: 'Stellar Dynamics LLC',
    businessId: 'b5',
    status: 'active',
    dateJoined: new Date('2025-01-20'),
    lastActive: new Date(now - day * 2),
  },
  {
    id: 'u13',
    fullName: 'Jordan Miles',
    email: 'jordan@stellar.llc',
    role: 'manager',
    businessName: 'Stellar Dynamics LLC',
    businessId: 'b5',
    status: 'active',
    dateJoined: new Date('2025-03-10'),
    lastActive: new Date(now - day * 5),
  },
  {
    id: 'u14',
    fullName: 'Sophie Martin',
    email: 'sophie@novatech.com',
    role: 'owner',
    businessName: 'NovaTech Solutions',
    businessId: 'b6',
    status: 'pending',
    dateJoined: new Date('2026-03-28'),
    lastActive: new Date(now - day * 1),
  },
  {
    id: 'u15',
    fullName: 'David Park',
    email: 'david@megacorp.io',
    role: 'owner',
    businessName: 'MegaCorp Industries',
    businessId: 'b7',
    status: 'active',
    dateJoined: new Date('2023-11-05'),
    lastActive: new Date(now - day * 0.4),
  },
  {
    id: 'u16',
    fullName: 'Michael Tran',
    email: 'michael@megacorp.io',
    role: 'admin',
    businessName: 'MegaCorp Industries',
    businessId: 'b7',
    status: 'active',
    dateJoined: new Date('2024-01-20'),
    lastActive: new Date(now - day * 1),
  },
  {
    id: 'u17',
    fullName: 'Jessica Roe',
    email: 'jessica@megacorp.io',
    role: 'manager',
    businessName: 'MegaCorp Industries',
    businessId: 'b7',
    status: 'active',
    dateJoined: new Date('2024-03-15'),
    lastActive: new Date(now - day * 2),
  },
  {
    id: 'u18',
    fullName: 'Brandon Lee',
    email: 'brandon@megacorp.io',
    role: 'employee',
    businessName: 'MegaCorp Industries',
    businessId: 'b7',
    status: 'suspended',
    dateJoined: new Date('2024-05-10'),
    lastActive: new Date(now - day * 60),
  },
  {
    id: 'u19',
    fullName: 'Laura Bennett',
    email: 'laura@pixelwave.co',
    role: 'owner',
    businessName: 'PixelWave Creative',
    businessId: 'b8',
    status: 'suspended',
    dateJoined: new Date('2025-06-14'),
    lastActive: new Date(now - day * 45),
  },
  {
    id: 'u20',
    fullName: "Ryan O'Brien",
    email: 'ryan@dataflow.ai',
    role: 'owner',
    businessName: 'DataFlow AI',
    businessId: 'b9',
    status: 'active',
    dateJoined: new Date('2024-09-03'),
    lastActive: new Date(now - day * 0.8),
  },
  {
    id: 'u21',
    fullName: 'Zoe Adams',
    email: 'zoe@dataflow.ai',
    role: 'employee',
    businessName: 'DataFlow AI',
    businessId: 'b9',
    status: 'active',
    dateJoined: new Date('2024-11-01'),
    lastActive: new Date(now - day * 3),
  },
  {
    id: 'u22',
    fullName: 'Aisha Patel',
    email: 'aisha@greenleaf.eco',
    role: 'owner',
    businessName: 'GreenLeaf Eco',
    businessId: 'b10',
    status: 'active',
    dateJoined: new Date('2026-01-12'),
    lastActive: new Date(now - day * 1),
  },
  {
    id: 'u23',
    fullName: 'Tom Fischer',
    email: 'tom@buildright.dev',
    role: 'owner',
    businessName: 'BuildRight Dev',
    businessId: 'b11',
    status: 'active',
    dateJoined: new Date('2024-11-17'),
    lastActive: new Date(now - day * 0.6),
  },
  {
    id: 'u24',
    fullName: 'Samantha Cruz',
    email: 'sam@buildright.dev',
    role: 'admin',
    businessName: 'BuildRight Dev',
    businessId: 'b11',
    status: 'active',
    dateJoined: new Date('2025-01-05'),
    lastActive: new Date(now - day * 2),
  },
  {
    id: 'u25',
    fullName: 'Derek Nguyen',
    email: 'derek@buildright.dev',
    role: 'employee',
    businessName: 'BuildRight Dev',
    businessId: 'b11',
    status: 'active',
    dateJoined: new Date('2025-02-20'),
    lastActive: new Date(now - day * 4),
  },
  {
    id: 'u26',
    fullName: 'Nina Kowalski',
    email: 'nina@brightpath.io',
    role: 'owner',
    businessName: 'BrightPath Analytics',
    businessId: 'b12',
    status: 'active',
    dateJoined: new Date('2024-02-25'),
    lastActive: new Date(now - day * 0.3),
  },
  {
    id: 'u27',
    fullName: 'Carlos Mendez',
    email: 'carlos@quickship.co',
    role: 'owner',
    businessName: 'QuickShip Logistics',
    businessId: 'b13',
    status: 'active',
    dateJoined: new Date('2025-04-09'),
    lastActive: new Date(now - day * 1.5),
  },
  {
    id: 'u28',
    fullName: 'Hannah Lee',
    email: 'hannah@artisan.market',
    role: 'owner',
    businessName: 'Artisan Market',
    businessId: 'b14',
    status: 'pending',
    dateJoined: new Date('2026-04-01'),
    lastActive: new Date(now - day * 0),
  },
  {
    id: 'u29',
    fullName: 'Oliver Grant',
    email: 'oliver@securelock.io',
    role: 'owner',
    businessName: 'SecureLock Systems',
    businessId: 'b15',
    status: 'active',
    dateJoined: new Date('2023-08-20'),
    lastActive: new Date(now - day * 0.5),
  },
  {
    id: 'u30',
    fullName: 'Fatima Al-Rashid',
    email: 'fatima@zenith.tech',
    role: 'owner',
    businessName: 'Zenith Technologies',
    businessId: 'b16',
    status: 'suspended',
    dateJoined: new Date('2024-07-30'),
    lastActive: new Date(now - day * 40),
  },
  {
    id: 'u31',
    fullName: 'Jake Morrison',
    email: 'jake@freshbyte.io',
    role: 'owner',
    businessName: 'FreshByte Apps',
    businessId: 'b17',
    status: 'active',
    dateJoined: new Date('2025-09-11'),
    lastActive: new Date(now - day * 2),
  },
  {
    id: 'u32',
    fullName: 'Amy Foster',
    email: 'amy@freshbyte.io',
    role: 'employee',
    businessName: 'FreshByte Apps',
    businessId: 'b17',
    status: 'active',
    dateJoined: new Date('2025-10-20'),
    lastActive: new Date(now - day * 5),
  },
  {
    id: 'u33',
    fullName: 'Chloe Dubois',
    email: 'chloe@luxeinterior.com',
    role: 'owner',
    businessName: 'Luxe Interior Design',
    businessId: 'b18',
    status: 'active',
    dateJoined: new Date('2024-12-05'),
    lastActive: new Date(now - day * 1),
  },
  {
    id: 'u34',
    fullName: 'Wei Chen',
    email: 'wei@quantumedge.ai',
    role: 'owner',
    businessName: 'QuantumEdge AI',
    businessId: 'b19',
    status: 'active',
    dateJoined: new Date('2023-06-15'),
    lastActive: new Date(now - day * 0.2),
  },
  {
    id: 'u35',
    fullName: 'Lisa Park',
    email: 'lisa@quantumedge.ai',
    role: 'admin',
    businessName: 'QuantumEdge AI',
    businessId: 'b19',
    status: 'active',
    dateJoined: new Date('2023-09-01'),
    lastActive: new Date(now - day * 1),
  },
  {
    id: 'u36',
    fullName: 'Megan Scott',
    email: 'megan@bloomhealth.co',
    role: 'owner',
    businessName: 'BloomHealth',
    businessId: 'b20',
    status: 'active',
    dateJoined: new Date('2025-02-18'),
    lastActive: new Date(now - day * 3),
  },
  {
    id: 'u37',
    fullName: 'Liam Nguyen',
    email: 'liam@codeforge.dev',
    role: 'owner',
    businessName: 'CodeForge Studios',
    businessId: 'b21',
    status: 'active',
    dateJoined: new Date('2024-08-22'),
    lastActive: new Date(now - day * 0.7),
  },
  {
    id: 'u38',
    fullName: 'Chris Yang',
    email: 'chris@codeforge.dev',
    role: 'manager',
    businessName: 'CodeForge Studios',
    businessId: 'b21',
    status: 'active',
    dateJoined: new Date('2024-10-15'),
    lastActive: new Date(now - day * 2),
  },
  {
    id: 'u39',
    fullName: 'Isabella Romano',
    email: 'isabella@vitaverde.eu',
    role: 'owner',
    businessName: 'VitaVerde Organics',
    businessId: 'b22',
    status: 'active',
    dateJoined: new Date('2026-02-10'),
    lastActive: new Date(now - day * 1),
  },
  {
    id: 'u40',
    fullName: 'Nathan Brooks',
    email: 'nathan@skyline.build',
    role: 'owner',
    businessName: 'Skyline Construction',
    businessId: 'b23',
    status: 'active',
    dateJoined: new Date('2023-12-01'),
    lastActive: new Date(now - day * 0.4),
  },
  {
    id: 'u41',
    fullName: 'Diana Ross',
    email: 'diana@skyline.build',
    role: 'admin',
    businessName: 'Skyline Construction',
    businessId: 'b23',
    status: 'active',
    dateJoined: new Date('2024-02-10'),
    lastActive: new Date(now - day * 1),
  },
  {
    id: 'u42',
    fullName: 'Patrick Moore',
    email: 'patrick@skyline.build',
    role: 'employee',
    businessName: 'Skyline Construction',
    businessId: 'b23',
    status: 'active',
    dateJoined: new Date('2024-05-20'),
    lastActive: new Date(now - day * 6),
  },
  {
    id: 'u43',
    fullName: 'Zara Khan',
    email: 'zara@pulsefit.io',
    role: 'owner',
    businessName: 'PulseFit Wellness',
    businessId: 'b24',
    status: 'pending',
    dateJoined: new Date('2026-03-15'),
    lastActive: new Date(now - day * 0),
  },
  {
    id: 'u44',
    fullName: 'Ethan Wolfe',
    email: 'ethan@ironcladops.com',
    role: 'owner',
    businessName: 'IronClad Operations',
    businessId: 'b25',
    status: 'suspended',
    dateJoined: new Date('2024-10-28'),
    lastActive: new Date(now - day * 50),
  },
  {
    id: 'u45',
    fullName: 'Maria Gonzalez',
    email: 'maria@ironcladops.com',
    role: 'employee',
    businessName: 'IronClad Operations',
    businessId: 'b25',
    status: 'suspended',
    dateJoined: new Date('2025-01-15'),
    lastActive: new Date(now - day * 50),
  },
];
